# Generated by Django 4.1.7 on 2023-03-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('cat_img', models.ImageField(default='', upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('subcat_img', models.ImageField(default='', upload_to='static/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_img', models.ImageField(default='', upload_to='static/images')),
                ('prod_spec', models.ImageField(default='', upload_to='static/images')),
                ('prod_desc', models.CharField(max_length=1000)),
                ('prod_price', models.IntegerField(default=0)),
                ('prod_date', models.DateField(auto_now_add=True)),
                ('prod_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro.subcategory')),
            ],
        ),
    ]
