# Generated by Django 4.1.7 on 2023-03-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0003_alter_category_cat_img_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(default='', upload_to='static/category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(default='', upload_to='static/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_spec',
            field=models.ImageField(default='', upload_to='static/specs'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcat_img',
            field=models.ImageField(default='', upload_to='static/subcategory'),
        ),
    ]
