# Generated by Django 4.1.7 on 2023-03-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0004_alter_category_cat_img_alter_product_prod_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sol_img', models.ImageField(default='', upload_to='static/solution')),
                ('spec_img', models.ImageField(default='', upload_to='static/solution')),
            ],
        ),
    ]
