# Generated by Django 4.1.7 on 2023-03-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0005_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_subcategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='subcats',
            field=models.ManyToManyField(blank=True, to='micro.subcategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='products',
            field=models.ManyToManyField(blank=True, to='micro.product'),
        ),
    ]
