# Generated by Django 4.1.7 on 2023-03-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0008_remove_category_subcats_remove_subcategory_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_brocher',
            field=models.FileField(default='', upload_to='static/specs'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_manual',
            field=models.FileField(default='', upload_to='static/specs'),
        ),
    ]
