# Generated by Django 4.1.7 on 2023-03-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0009_product_prod_brocher_product_prod_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_brocher',
            field=models.FileField(default='', upload_to='static/brocher'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_manual',
            field=models.FileField(default='', upload_to='static/manual'),
        ),
    ]
