# Generated by Django 4.1.7 on 2023-03-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0010_alter_product_prod_brocher_alter_product_prod_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_brocher',
            field=models.FileField(blank=True, default='', null=True, upload_to='static/brocher'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_desc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_manual',
            field=models.FileField(blank=True, default='', null=True, upload_to='static/manual'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_spec',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/specs'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='spec_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/solution'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
