# Generated by Django 4.1.7 on 2023-07-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0011_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='public_id',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='public_id',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='public_id',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
