# Generated by Django 4.1.7 on 2023-07-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0012_category_public_id_product_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='public_id',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
