# Generated by Django 4.1.7 on 2023-07-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0013_solution_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(default='', upload_to='media/category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_brocher',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/brocher'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(default='', upload_to='media/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_manual',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/manual'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_spec',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/specs'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='sol_img',
            field=models.ImageField(default='', upload_to='media/solution'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='spec_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/solution'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcat_img',
            field=models.ImageField(default='', upload_to='media/subcategory'),
        ),
    ]
