# Generated by Django 4.1.7 on 2023-07-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0014_alter_category_cat_img_alter_product_prod_brocher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(default='', upload_to='static/category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_brocher',
            field=models.FileField(blank=True, default='', null=True, upload_to='static/brocher'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(default='', upload_to='static/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_manual',
            field=models.FileField(blank=True, default='', null=True, upload_to='static/manual'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_spec',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/specs'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='sol_img',
            field=models.ImageField(default='', upload_to='static/solution'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='spec_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/solution'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcat_img',
            field=models.ImageField(default='', upload_to='static/subcategory'),
        ),
    ]
