# Generated by Django 4.1.7 on 2023-07-07 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0015_alter_category_cat_img_alter_product_prod_brocher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_subcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='prod_data', to='micro.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subcat_data', to='micro.category'),
        ),
    ]
